### ISSUE TITLE
Improve Finder's Frontend Features

### ISSUE THREAD

**Issue by aizeorg** [aizeorg/finder-react#1]
### Objectives:
Enhance the result presentation by adding a dynamic column selector.
Improve the dynamic filtering feature by incorporating metadata.
Possibility to have the search state stored in local storage.

### **Acceptance Criteria:**

- [ ] All selected columns should display correctly. https://github.com/aizeorg/finder-react/issues/3
- [ ] Filters should accurately represent the current dataset, including unavailable options. https://github.com/aizeorg/finder-react/issues/4
- [ ] We can fetch the last stored state from local storage. https://github.com/aizeorg/finder-react/issues/1

### User Stories:
As a user, I should be able to select the columns I want to see in the result section. 
As a user, I should be able to see which filter options are not available based on the current dataset.
As a user, Enable storing last filter state in local storage

### Implementation Details
Utilize the /meta API for fetching metadata for column and filter options.
Utilize the /search API for fetching search results and current available filter options.
Utilise the local storage and newly create state model to store search state in store last used search state.

### **Documentation:**
API Specifications

>  Meta
<details>
<summary> Meta API </summary>

```javascript

```javascript
{
  "CALIBRATED RANGE MAX": {
    "dataType": "number",
    "max": 220,
    "min": 180,
    "values": [215.87, 181.6, 194.28, 213.75, 191, 189.62, 216.28, 180.09, 202.56, 197.77, 187.31, 196.09, 187.03]
  },
  "CALIBRATED RANGE MAX_UOM": {
    "dataType": "string",
    "values": ["PoC", "oC", "oF"]
  },
    "I/O TYPE": {
        "dataType": "string",
        "values": [
            "DI",
            "AI",
            "AO",
            "DO"
        ]
    },
    "System": {
        "dataType": "string",
        "values": [
            "22: Sanitation Disposal system",
            "32: Material uploading Sys",
            "31: Sub mechanical Sys",
            "21: CRUDE HANDLING AND METERING",
            "23: UTILITIES",
            "77: Ventisjon Sys",
            "11: Crane and fabrication",
            "44: Some other sys",
            "22: GAS PROCESSING"
        ]
    },
    "Discipline": {
        "dataType": "string",
        "values": [
            "A: Assemply and Installation",
            "E: Electrical",
            "I: Industrial equipments",
            "F: Facility handling",
            "C: Crane and material",
            "J: Jagan and magan",
            "B: Biomarine and sanity",
            "G: Gaseous sabstances",
            "D: Gas and toxic substance"
        ]
    },

}

``` 
</details>

> Search

<details>
  <summary>Search API spec</summary>
  
```javascript
{
    "hits": 755,
    "results": [
        {
            "SET POINT HIGH HIGH": 162.46,
            "sapParentAvevaExternalId": "10e84d47-b43c-4133-8ed5-c6221461382a",
            "Issued By": "Vaibhav",
            "Owner": "Person A",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 6 HJ",
            "PART NUMBER": "rne7r3d0s3",
            "source": "external",
            "flocBarrierElementPrimary": "ioq3xyiawfps",
            "CALIBRATED RANGE MAX_UOM": "oC",
            "SERIAL NUMBER": "ccbfa7d3-a9ec-4a9f-8398-1bb3ab24ac30",
            "SIGNAL TYPE": "4-20mA",
            "HAZARDOUS AREA CERT NUMBER": "govcl5354j7q",
            "createdTime": "2023-08-25T09:57:42.980Z",
            "SUPPLY CODE": "ASIA",
            "state": "0",
            "id": 8679836,
            "flocFunctionalLocation": "9b47ryx24i",
            "WEIGHT (DRY)": 2.09,
            "MODEL NUMBER": "etq6wxo",
            "I/O TYPE": "AI",
            "System": "32: Material uploading Sys",
            "Discipline": "E: Electrical",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
            "PARENT TAG": "to0g1wz9vn",
            "flocSystemId": 95,
            "SET POINT HIGH HIGH_UOM": "oF",
            "flocLocation": "b3ql",
            "SAP CATALOG PROFILE": "y3fl8w37",
            "FIRE AREA": "0gbg",
            "CALIBRATED RANGE MAX": 181.6,
            "LAST MAINTENANCE DATE": "2023-08-24T08:52:26.725Z",
            "CALIBRATION DATE": "2023-08-17T21:36:26.091Z",
            "LAST INSPECTION DATE": "2023-08-29T05:11:48.844Z"
        },
        {
            "SET POINT HIGH HIGH": 151.44,
            "sapParentAvevaExternalId": "9e0f4bd1-319d-4392-b67d-be6d79c178eb",
            "Issued By": "Vaibhav",
            "Owner": "Person D",
            "SAP OBJECT TYPE": "IP-TIUT",
            "HAZARDOUS ATEX MARKING": "II 6 HJ",
            "PART NUMBER": "ol92a89hzb",
            "source": "sap",
            "flocBarrierElementPrimary": "96okvx527ozf",
            "CALIBRATED RANGE MAX_UOM": "oF",
            "SERIAL NUMBER": "b78febf1-1e04-41ac-b641-70f3d2458c8c",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "gm310y3agbbj",
            "createdTime": "2023-09-16T06:49:34.985Z",
            "SUPPLY CODE": "NA",
            "state": "1",
            "id": 8880505,
            "flocFunctionalLocation": "sa3ocifyzt",
            "WEIGHT (DRY)": 2.16,
            "MODEL NUMBER": "5s6eac1",
            "I/O TYPE": "AO",
            "System": "32: Material uploading Sys",
            "Discipline": "F: Facility handling",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
            "PARENT TAG": "33yebm0gvl",
            "flocSystemId": 32,
            "SET POINT HIGH HIGH_UOM": "oL",
            "flocLocation": "n8mi",
            "SAP CATALOG PROFILE": "x131fdua",
            "FIRE AREA": "u8j2",
            "CALIBRATED RANGE MAX": 213.75,
            "LAST MAINTENANCE DATE": "2023-09-05T08:55:48.797Z",
            "CALIBRATION DATE": "2023-09-16T16:28:39.467Z",
            "LAST INSPECTION DATE": "2023-08-28T10:55:50.299Z"
        },
        {
            "SET POINT HIGH HIGH": 163.13,
            "sapParentAvevaExternalId": "5846f887-cd73-469b-afd6-d75509ec7fc0",
            "Issued By": "Vaibhav",
            "Owner": "Person B",
            "SAP OBJECT TYPE": "IP-IOFT",
            "HAZARDOUS ATEX MARKING": "II 9 GIJO",
            "PART NUMBER": "j9p4bsowy2",
            "source": "sap",
            "flocBarrierElementPrimary": "4r225kippwao",
            "CALIBRATED RANGE MAX_UOM": "oF",
            "SERIAL NUMBER": "f288b85a-6814-4f78-a7dc-85c4cc6138fb",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "is5rhcuyfvtr",
            "createdTime": "2023-09-16T20:39:15.703Z",
            "SUPPLY CODE": "EU",
            "state": "1",
            "id": 8888039,
            "flocFunctionalLocation": "cy09m7oat2",
            "WEIGHT (DRY)": 2.4,
            "MODEL NUMBER": "g0rktzz",
            "I/O TYPE": "DO",
            "System": "31: Sub mechanical Sys",
            "Discipline": "G: Gaseous sabstances",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
            "PARENT TAG": "9im8s7svcq",
            "flocSystemId": 46,
            "SET POINT HIGH HIGH_UOM": "oL",
            "flocLocation": "ov15",
            "SAP CATALOG PROFILE": "r9r3ern6",
            "FIRE AREA": "01lu",
            "CALIBRATED RANGE MAX": 187.31,
            "LAST MAINTENANCE DATE": "2023-08-28T13:01:53.751Z",
            "CALIBRATION DATE": "2023-08-24T11:39:19.810Z",
            "LAST INSPECTION DATE": "2023-08-24T14:28:26.365Z"
        },
        {
            "SET POINT HIGH HIGH": 155.08,
            "sapParentAvevaExternalId": "7f1fe2f2-2ad6-4b49-a480-7e9ff110d8c3",
            "Issued By": "Vaibhav",
            "Owner": "Person A",
            "SAP OBJECT TYPE": "IP-IOFT",
            "HAZARDOUS ATEX MARKING": "II 4 F",
            "PART NUMBER": "g34c7tu04l",
            "source": "aveva",
            "flocBarrierElementPrimary": "ulmgmpyoyyac",
            "CALIBRATED RANGE MAX_UOM": "oC",
            "SERIAL NUMBER": "a136a0c3-c119-495f-8285-b4cc4c014050",
            "SIGNAL TYPE": "Modbus",
            "HAZARDOUS AREA CERT NUMBER": "te56ztqkjznh",
            "createdTime": "2023-08-24T16:19:55.578Z",
            "SUPPLY CODE": "EU",
            "state": "1",
            "id": 8970544,
            "flocFunctionalLocation": "wmaotgqskf",
            "WEIGHT (DRY)": 2.39,
            "MODEL NUMBER": "3u7gvwo",
            "I/O TYPE": "AO",
            "System": "77: Ventisjon Sys",
            "Discipline": "A: Assemply and Installation",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
            "PARENT TAG": "bho2z6hdud",
            "flocSystemId": 66,
            "SET POINT HIGH HIGH_UOM": "oC",
            "flocLocation": "3lg5",
            "SAP CATALOG PROFILE": "9sv7n4t8",
            "FIRE AREA": "d9j9",
            "CALIBRATED RANGE MAX": 199.69,
            "LAST MAINTENANCE DATE": "2023-08-19T17:48:19.423Z",
            "CALIBRATION DATE": "2023-09-20T18:01:52.836Z",
            "LAST INSPECTION DATE": "2023-09-14T07:20:06.334Z"
        },
        {
            "SET POINT HIGH HIGH": 162.35,
            "sapParentAvevaExternalId": "5a88ef19-1920-44d3-b35d-59a657ff3fb8",
            "Issued By": "Vaibhav",
            "Owner": "Person D",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 4 F",
            "PART NUMBER": "eyhtgthvr0",
            "source": "aveva",
            "flocBarrierElementPrimary": "ei3azdok2mrp",
            "CALIBRATED RANGE MAX_UOM": "oC",
            "SERIAL NUMBER": "09372ab8-c68d-4edf-8c59-b27cb4175e4c",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "nkqlcxnu636a",
            "createdTime": "2023-08-23T05:29:45.084Z",
            "SUPPLY CODE": "ASIA",
            "state": "1",
            "id": 8081451,
            "flocFunctionalLocation": "lzwj60kcfk",
            "WEIGHT (DRY)": 2.7,
            "MODEL NUMBER": "7ldy0jz",
            "I/O TYPE": "DO",
            "System": "22: Sanitation Disposal system",
            "Discipline": "A: Assemply and Installation",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "7n7fdon8h2",
            "flocSystemId": 33,
            "SET POINT HIGH HIGH_UOM": "iY",
            "flocLocation": "psxz",
            "SAP CATALOG PROFILE": "nhul07xx",
            "FIRE AREA": "0b2z",
            "CALIBRATED RANGE MAX": 218.3,
            "LAST MAINTENANCE DATE": "2023-09-15T16:54:19.907Z",
            "CALIBRATION DATE": "2023-09-07T10:20:55.386Z",
            "LAST INSPECTION DATE": "2023-09-02T03:15:43.976Z"
        },
        {
            "SET POINT HIGH HIGH": 155.08,
            "sapParentAvevaExternalId": "3e4c702b-5c7e-48c1-8869-9ee695e13451",
            "Issued By": "Vaibhav",
            "Owner": "Person D",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 4 F",
            "PART NUMBER": "6mqedz3av4",
            "source": "aveva",
            "flocBarrierElementPrimary": "qp1a3y0yz02b",
            "CALIBRATED RANGE MAX_UOM": "oF",
            "SERIAL NUMBER": "28e2aada-52ad-4b1a-ab09-6684d074057a",
            "SIGNAL TYPE": "4-20mA",
            "HAZARDOUS AREA CERT NUMBER": "zqq6816iq83a",
            "createdTime": "2023-09-14T19:06:43.030Z",
            "SUPPLY CODE": "EU",
            "state": "0",
            "id": 8975383,
            "flocFunctionalLocation": "64ufdlyj8r",
            "WEIGHT (DRY)": 2.83,
            "MODEL NUMBER": "8u2gzfc",
            "I/O TYPE": "DO",
            "System": "11: Crane and fabrication",
            "Discipline": "E: Electrical",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
            "PARENT TAG": "0g45gyc5gq",
            "flocSystemId": 20,
            "SET POINT HIGH HIGH_UOM": "oL",
            "flocLocation": "3ovr",
            "SAP CATALOG PROFILE": "8lgdng3m",
            "FIRE AREA": "npa5",
            "CALIBRATED RANGE MAX": 205.38,
            "LAST MAINTENANCE DATE": "2023-08-25T04:48:50.402Z",
            "CALIBRATION DATE": "2023-09-11T21:35:18.636Z",
            "LAST INSPECTION DATE": "2023-08-29T13:49:36.485Z"
        },
        {
            "SET POINT HIGH HIGH": 157.36,
            "sapParentAvevaExternalId": "e5b676b7-c2dc-45bd-824d-34cb75587608",
            "Issued By": "Vaibhav",
            "Owner": "Person B",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 2 G",
            "PART NUMBER": "vkhopgd7w5",
            "source": "external",
            "flocBarrierElementPrimary": "ss6bhfadjjjh",
            "CALIBRATED RANGE MAX_UOM": "oC",
            "SERIAL NUMBER": "71461776-dff7-4517-ae71-378031b05c21",
            "SIGNAL TYPE": "4-20mA",
            "HAZARDOUS AREA CERT NUMBER": "fe6oewb89832",
            "createdTime": "2023-09-13T01:02:44.943Z",
            "SUPPLY CODE": "EU",
            "state": "0",
            "id": 8181866,
            "flocFunctionalLocation": "979pdjzffo",
            "WEIGHT (DRY)": 2.34,
            "MODEL NUMBER": "yhmpyhs",
            "I/O TYPE": "AO",
            "System": "44: Some other sys",
            "Discipline": "E: Electrical",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T5",
            "PARENT TAG": "2lainzrxp1",
            "flocSystemId": 33,
            "SET POINT HIGH HIGH_UOM": "oC",
            "flocLocation": "k5t7",
            "SAP CATALOG PROFILE": "sriv0z9l",
            "FIRE AREA": "cyjw",
            "CALIBRATED RANGE MAX": 211.47,
            "LAST MAINTENANCE DATE": "2023-09-17T10:02:51.779Z",
            "CALIBRATION DATE": "2023-09-19T01:07:46.333Z",
            "LAST INSPECTION DATE": "2023-08-19T17:59:35.619Z"
        },
        {
            "SET POINT HIGH HIGH": 151.88,
            "sapParentAvevaExternalId": "91e7a357-ebe2-4796-88ce-ad5ffbde228d",
            "Issued By": "Vaibhav",
            "Owner": "Person A",
            "SAP OBJECT TYPE": "IP-IOFT",
            "HAZARDOUS ATEX MARKING": "II 3 G",
            "PART NUMBER": "r8dtx4luum",
            "source": "aveva",
            "flocBarrierElementPrimary": "u99pr2jvz2fh",
            "CALIBRATED RANGE MAX_UOM": "oF",
            "SERIAL NUMBER": "69d6a369-4e6e-4eef-bb74-d71ab68fca12",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "j5smcmz7ufla",
            "createdTime": "2023-08-16T23:36:22.141Z",
            "SUPPLY CODE": "EU",
            "state": "1",
            "id": 8926553,
            "flocFunctionalLocation": "kbz74vogmw",
            "WEIGHT (DRY)": 2.22,
            "MODEL NUMBER": "5c7vbp5",
            "I/O TYPE": "AI",
            "System": "77: Ventisjon Sys",
            "Discipline": "E: Electrical",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "mw3dxjkafv",
            "flocSystemId": 54,
            "SET POINT HIGH HIGH_UOM": "oF",
            "flocLocation": "uv1j",
            "SAP CATALOG PROFILE": "7y3ptu62",
            "FIRE AREA": "bqpz",
            "CALIBRATED RANGE MAX": 203.26,
            "LAST MAINTENANCE DATE": "2023-08-24T18:47:58.484Z",
            "CALIBRATION DATE": "2023-08-24T18:08:57.199Z",
            "LAST INSPECTION DATE": "2023-08-26T04:32:32.418Z"
        },
        {
            "SET POINT HIGH HIGH": 163.82,
            "sapParentAvevaExternalId": "8be050fc-af5a-4c7b-858b-7cc137216e4f",
            "Issued By": "Vaibhav",
            "Owner": "Person C",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 12 oiu",
            "PART NUMBER": "9277mptljh",
            "source": "aveva",
            "flocBarrierElementPrimary": "6ai4r6agkiql",
            "CALIBRATED RANGE MAX_UOM": "oF",
            "SERIAL NUMBER": "4e606750-11ef-4f97-a2df-ca2f0c1934e5",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "1jwh5hl9q3d7",
            "createdTime": "2023-08-18T06:55:58.190Z",
            "SUPPLY CODE": "EU",
            "state": "0",
            "id": 8199986,
            "flocFunctionalLocation": "mon2np6tqk",
            "WEIGHT (DRY)": 2.66,
            "MODEL NUMBER": "wa8v1ad",
            "I/O TYPE": "AI",
            "System": "31: Sub mechanical Sys",
            "Discipline": "G: Gaseous sabstances",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "lkhlcj7zc9",
            "flocSystemId": 62,
            "SET POINT HIGH HIGH_UOM": "oL",
            "flocLocation": "fayy",
            "SAP CATALOG PROFILE": "7olrskx6",
            "FIRE AREA": "ulu0",
            "CALIBRATED RANGE MAX": 194.93,
            "LAST MAINTENANCE DATE": "2023-09-20T11:48:58.662Z",
            "CALIBRATION DATE": "2023-08-19T09:46:41.044Z",
            "LAST INSPECTION DATE": "2023-09-01T06:42:05.068Z"
        },
        {
            "SET POINT HIGH HIGH": 167.27,
            "sapParentAvevaExternalId": "a8d89ded-f293-46ca-a7ca-5da38c6c697e",
            "Issued By": "Vaibhav",
            "Owner": "Person B",
            "SAP OBJECT TYPE": "IP-TIUT",
            "HAZARDOUS ATEX MARKING": "II 1 G",
            "PART NUMBER": "a4s6sinkim",
            "source": "ION",
            "flocBarrierElementPrimary": "p8uu06280qd2",
            "CALIBRATED RANGE MAX_UOM": "oF",
            "SERIAL NUMBER": "beeb528d-9f9e-40bc-be04-aa7f6dc8bcfd",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "l2mnvkkoyfix",
            "createdTime": "2023-08-19T10:46:07.670Z",
            "SUPPLY CODE": "ASIA",
            "state": "1",
            "id": 8018692,
            "flocFunctionalLocation": "5fj2ciacrh",
            "WEIGHT (DRY)": 2.81,
            "MODEL NUMBER": "blq184f",
            "I/O TYPE": "DO",
            "System": "22: GAS PROCESSING",
            "Discipline": "A: Assemply and Installation",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "yq62rdozvg",
            "flocSystemId": 72,
            "SET POINT HIGH HIGH_UOM": "oF",
            "flocLocation": "ggt8",
            "SAP CATALOG PROFILE": "7iu0380e",
            "FIRE AREA": "euob",
            "CALIBRATED RANGE MAX": 193.83,
            "LAST MAINTENANCE DATE": "2023-09-15T21:34:37.138Z",
            "CALIBRATION DATE": "2023-08-21T08:25:35.037Z",
            "LAST INSPECTION DATE": "2023-09-01T15:48:56.642Z"
        },
        {
            "SET POINT HIGH HIGH": 157.93,
            "sapParentAvevaExternalId": "315fd660-e590-4e50-9a54-f878a7191484",
            "Issued By": "Vaibhav",
            "Owner": "Person D",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 6 HJ",
            "PART NUMBER": "scbp78rbze",
            "source": "aveva",
            "flocBarrierElementPrimary": "5lukp0byup8v",
            "CALIBRATED RANGE MAX_UOM": "oC",
            "SERIAL NUMBER": "dc763a74-2eb9-4a54-bb2f-100f4448d860",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "x2sgdu0vrl7a",
            "createdTime": "2023-08-27T11:27:48.318Z",
            "SUPPLY CODE": "EU",
            "state": "0",
            "id": 8715882,
            "flocFunctionalLocation": "130qx86rqw",
            "WEIGHT (DRY)": 2.59,
            "MODEL NUMBER": "wvrlmvh",
            "I/O TYPE": "DO",
            "System": "31: Sub mechanical Sys",
            "Discipline": "D: Gas and toxic substance",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
            "PARENT TAG": "3756etnoxc",
            "flocSystemId": 75,
            "SET POINT HIGH HIGH_UOM": "oF",
            "flocLocation": "8wkw",
            "SAP CATALOG PROFILE": "mudr15s5",
            "FIRE AREA": "ocbr",
            "CALIBRATED RANGE MAX": 187.6,
            "LAST MAINTENANCE DATE": "2023-08-27T12:18:09.899Z",
            "CALIBRATION DATE": "2023-09-14T08:33:14.182Z",
            "LAST INSPECTION DATE": "2023-09-08T12:33:47.010Z"
        },
        {
            "SET POINT HIGH HIGH": 163.49,
            "sapParentAvevaExternalId": "e0b5f462-d0c0-42c4-ad18-c252535e6300",
            "Issued By": "Vaibhav",
            "Owner": "Person A",
            "SAP OBJECT TYPE": "IP-IOFT",
            "HAZARDOUS ATEX MARKING": "II 39 OI",
            "PART NUMBER": "mgy95ywnnp",
            "source": "ION",
            "flocBarrierElementPrimary": "yaapamvtmuew",
            "CALIBRATED RANGE MAX_UOM": "oC",
            "SERIAL NUMBER": "d07b0ba3-7e1d-4c6c-b71b-983a68c0427e",
            "SIGNAL TYPE": "4-20mA",
            "HAZARDOUS AREA CERT NUMBER": "cp4yqiv236vk",
            "createdTime": "2023-09-08T09:15:46.854Z",
            "SUPPLY CODE": "ASIA",
            "state": "1",
            "id": 8688822,
            "flocFunctionalLocation": "nzs9q8vd0d",
            "WEIGHT (DRY)": 2.53,
            "MODEL NUMBER": "ot0v9d8",
            "I/O TYPE": "DO",
            "System": "23: UTILITIES",
            "Discipline": "F: Facility handling",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "hp20ffyn48",
            "flocSystemId": 42,
            "SET POINT HIGH HIGH_UOM": "oC",
            "flocLocation": "nzny",
            "SAP CATALOG PROFILE": "sglop6aj",
            "FIRE AREA": "47p1",
            "CALIBRATED RANGE MAX": 216.42,
            "LAST MAINTENANCE DATE": "2023-09-10T12:54:22.379Z",
            "CALIBRATION DATE": "2023-09-17T21:53:30.598Z",
            "LAST INSPECTION DATE": "2023-09-14T15:08:47.084Z"
        },
        {
            "SET POINT HIGH HIGH": 166.16,
            "sapParentAvevaExternalId": "13a41447-2880-433b-a0ba-4694906dd13b",
            "Issued By": "Vaibhav",
            "Owner": "Person D",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 2 G",
            "PART NUMBER": "bw8dc6ql1g",
            "source": "ION",
            "flocBarrierElementPrimary": "c5j5bu01h6bf",
            "CALIBRATED RANGE MAX_UOM": "PoC",
            "SERIAL NUMBER": "830ea4d2-76de-4123-bb1d-f6429f18f68e",
            "SIGNAL TYPE": "Modbus",
            "HAZARDOUS AREA CERT NUMBER": "rwj3lm03j9zo",
            "createdTime": "2023-09-13T19:56:32.342Z",
            "SUPPLY CODE": "NA",
            "state": "0",
            "id": 8346446,
            "flocFunctionalLocation": "300huwxr6p",
            "WEIGHT (DRY)": 2.08,
            "MODEL NUMBER": "wkipp6x",
            "I/O TYPE": "DO",
            "System": "22: GAS PROCESSING",
            "Discipline": "B: Biomarine and sanity",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "l8cype36vu",
            "flocSystemId": 89,
            "SET POINT HIGH HIGH_UOM": "iY",
            "flocLocation": "4k40",
            "SAP CATALOG PROFILE": "9zr9vdns",
            "FIRE AREA": "aa30",
            "CALIBRATED RANGE MAX": 200.48,
            "LAST MAINTENANCE DATE": "2023-08-28T10:57:36.075Z",
            "CALIBRATION DATE": "2023-09-10T02:19:49.381Z",
            "LAST INSPECTION DATE": "2023-08-19T20:59:10.576Z"
        },
        {
            "SET POINT HIGH HIGH": 160.77,
            "sapParentAvevaExternalId": "a428a3bc-5433-41c7-a3c9-804c1db877de",
            "Issued By": "Vaibhav",
            "Owner": "Person C",
            "SAP OBJECT TYPE": "IP-KJPT",
            "HAZARDOUS ATEX MARKING": "II 9 GIJO",
            "PART NUMBER": "amrncuh38m",
            "source": "sap",
            "flocBarrierElementPrimary": "vyg6qp7oxw5y",
            "CALIBRATED RANGE MAX_UOM": "PoC",
            "SERIAL NUMBER": "1f093362-99dd-40da-a0e2-5718d4824b33",
            "SIGNAL TYPE": "4-20mA",
            "HAZARDOUS AREA CERT NUMBER": "dn9m7r4e5gol",
            "createdTime": "2023-08-21T01:44:32.076Z",
            "SUPPLY CODE": "ASIA",
            "state": "1",
            "id": 8216842,
            "flocFunctionalLocation": "9nvc5g5lxk",
            "WEIGHT (DRY)": 2.92,
            "MODEL NUMBER": "wo9kpz1",
            "I/O TYPE": "DI",
            "System": "23: UTILITIES",
            "Discipline": "B: Biomarine and sanity",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T6",
            "PARENT TAG": "2ta1nprmw1",
            "flocSystemId": 19,
            "SET POINT HIGH HIGH_UOM": "iY",
            "flocLocation": "qu8f",
            "SAP CATALOG PROFILE": "fdaofsah",
            "FIRE AREA": "9ycs",
            "CALIBRATED RANGE MAX": 180.47,
            "LAST MAINTENANCE DATE": "2023-08-21T12:55:19.484Z",
            "CALIBRATION DATE": "2023-09-20T09:43:52.499Z",
            "LAST INSPECTION DATE": "2023-09-04T05:55:56.983Z"
        },
        {
            "SET POINT HIGH HIGH": 153.98,
            "sapParentAvevaExternalId": "84c1503b-2823-42f6-88ab-00287d7adb07",
            "Issued By": "Vaibhav",
            "Owner": "Person D",
            "SAP OBJECT TYPE": "IP-TIUT",
            "HAZARDOUS ATEX MARKING": "II 3 G",
            "PART NUMBER": "vdsu13poxx",
            "source": "sap",
            "flocBarrierElementPrimary": "mto3fusxb4i4",
            "CALIBRATED RANGE MAX_UOM": "PoC",
            "SERIAL NUMBER": "7f1dfd16-844b-43ec-8607-bea8ae9ef643",
            "SIGNAL TYPE": "0-10V",
            "HAZARDOUS AREA CERT NUMBER": "oeo6mcobptws",
            "createdTime": "2023-08-17T00:38:58.400Z",
            "SUPPLY CODE": "EU",
            "state": "1",
            "id": 8021598,
            "flocFunctionalLocation": "gd9v6pftqj",
            "WEIGHT (DRY)": 2.95,
            "MODEL NUMBER": "xqn4lfo",
            "I/O TYPE": "AI",
            "System": "77: Ventisjon Sys",
            "Discipline": "F: Facility handling",
            "HAZARDOUS AREA TEMP RATING (AS REQUIRED)": "T4",
            "PARENT TAG": "7bfaf58ppb",
            "flocSystemId": 89,
            "SET POINT HIGH HIGH_UOM": "oL",
            "flocLocation": "4q40",
            "SAP CATALOG PROFILE": "rqdrfnix",
            "FIRE AREA": "l3gc",
            "CALIBRATED RANGE MAX": 182.08,
            "LAST MAINTENANCE DATE": "2023-09-03T11:56:23.996Z",
            "CALIBRATION DATE": "2023-08-28T04:24:43.300Z",
            "LAST INSPECTION DATE": "2023-09-05T23:31:27.328Z"
        }
    ],
    "aggregations": {
        "System": {
            "32: Material uploading Sys": 85,
            "31: Sub mechanical Sys": 87,
            "77: Ventisjon Sys": 81,
            "22: Sanitation Disposal system": 78,
            "11: Crane and fabrication": 81,
            "44: Some other sys": 92,
            "22: GAS PROCESSING": 80,
            "23: UTILITIES": 79,
            "21: CRUDE HANDLING AND METERING": 92
        },
        "Discipline": {
            "E: Electrical": 87,
            "F: Facility handling": 83,
            "G: Gaseous sabstances": 82,
            "A: Assemply and Installation": 69,
            "D: Gas and toxic substance": 78,
            "B: Biomarine and sanity": 107,
            "C: Crane and material": 84,
            "I: Industrial equipments": 90,
            "J: Jagan and magan": 75
        }
    },
    "stats": {
        "CALIBRATED RANGE MAX": {
            "min": 180,
            "max": 220
        }
    }
}
``` 
</details>

Frontend Codebase Overview
Component Library Documentation

### **Milestones:**
Complete column selection feature.
Complete enhanced dynamic filtering feature.
Complete the search state storage in localstorage
